APP_NAME="ChatRocket"
APP_DEV_MODE=true
APP_NODE="127.0.0.1"
APP_GO_COROUTINES=100000
WEBSOCKET_PORT="9123"
TCP_PORT="8000"
GRPC_PORT="8002"
SWAGGER_PORT="9502"
LOG_ADDRESS="././logs/"

DB_HOST="127.0.0.1"
DB_PORT="3306"
DB_DATABASE="chat"
DB_USERNAME="root"
DB_PASSWORD="123456789"
DB_LOC="Asia/Shanghai"

REDIS_HOST="127.0.0.1"
REDIS_PORT="6379"
REDIS_PASSWORD=""
REDIS_DB=0

RABBITMQ_HOST="127.0.0.1"
RABBITMQ_PORT="5672"
RABBITMQ_USER="guest"
RABBITMQ_PASSWORD="guest"

JWT_SECRET="IJjkK2343267PQX12R-"
JWT_EXPIRES=685200
BASE64_ENCRYPT=""

APP_CLUSTER_MODEL=true